### ISSUE TITLE
Excess whitespace above GPA

### ISSUE THREAD

**Issue by mc10** [ets-berkeley-edu/calcentral#3891]
There's some extra whitespace above the GPA which is probably unnecessary.

![Screenshot](http://i.imgur.com/re6Bz6A.png)

**Comment by flint-hahn** [comment]
The intention of the space between the name and GPA / academic information
is in consideration of the height of the photo and visually utilizing the
white space effectively. If one were to change this, I'd drop the name down
to occupy the current white space instead of bringing up the academic
information.


On Wed, Jun 10, 2015 at 9:42 AM, Kevin Ji <notifications@github.com> wrote:

> There's some extra whitespace above the GPA which is probably unnecessary.
>
> [image: Screenshot]
> <https://camo.githubusercontent.com/874608784c19926367ea84566cf380e11390ec35/687474703a2f2f692e696d6775722e636f6d2f726536427a36412e706e67>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ets-berkeley-edu/calcentral/issues/3891>.
>



-- 

Flint Hahn
UX Designer
University of California, Berkeley
Student  Information System (SIS) Project
2850 Telegraph Ave., 6th Floor
Berkeley, CA 94705
Phone: 510.710.6786
sisproject.berkeley.edu

**Comment by raydavis** [comment]
For reference, here's how the layout looks in context:

![profile-with-photo](https://cloud.githubusercontent.com/assets/98528/8089176/13b7dbb2-0f5b-11e5-8872-199e5436fac6.png)

**Comment by mc10** [comment]
I guess it's only a problem when the major name is something long like "Electrical Engineering and Computer Science", because the text actually stretches past the profile picture, making it look a bit ugly.

**Comment by raydavis** [comment]
Ah, that makes sense, @mc10 -- thank you for clarifying! Visually the effect we're after is bottom-alignment, but our current static padding value isn't the most reliable solution.

**Comment by christianvuerings** [comment]
@paulkerschen didn't you recently fix this issue?

**Comment by paulkerschen** [comment]
Thanks for the reminder, @christianvuerings. Yes, the redesign in implemented in #4973 obviates this alignment issue.

**Comment by paulkerschen** [comment]
<img width="293" alt="screen shot 2016-03-04 at 1 39 10 pm" src="https://cloud.githubusercontent.com/assets/2413467/13540988/89788eec-e20e-11e5-953f-a77cb3465909.png">
